/* ===========================================================
   Quiz Bank — 60 questions
   Scoring: show 20 random questions per attempt. Each option
   awards points to primary (+3), related (+2) and sometimes a
   tertiary (+1) personality. Source: WanderWise Chapters 3A–3C.
   =========================================================== */

const QUIZ_BANK = [
  { id: 1, text: 'What excites you most about traveling?', options: [
    { key: 'A', text: 'Conquering mountains', points: { Explorer: 3, Nature: 2, Budget: 1 } },
    { key: 'B', text: 'Exploring history', points: { Culture: 3, Slow: 2, Foodie: 1 } },
    { key: 'C', text: 'Relaxing on a beach', points: { Beach: 3, Luxury: 2, Slow: 1 } },
    { key: 'D', text: 'Experiencing city life', points: { Urban: 3, Social: 2, Foodie: 1 } },
    { key: 'E', text: 'Escaping into nature', points: { Nature: 3, Slow: 2, Explorer: 1 } },
  ]},
  { id: 2, text: 'Where would you go if you had a free week tomorrow?', options: [
    { key: 'A', text: 'Ladakh', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Kyoto', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Maldives', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Tokyo', points: { Urban: 3, Foodie: 2, Social: 1 } },
    { key: 'E', text: 'Norway Fjords', points: { Nature: 3, Explorer: 2 } },
  ]},
  { id: 3, text: 'Which travel photo would you frame?', options: [
    { key: 'A', text: 'Mountain summit', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Ancient monument', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Beach sunset', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'City skyline', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Waterfall', points: { Nature: 3, Explorer: 1 } },
  ]},
  { id: 4, text: 'What makes you instantly book a trip?', options: [
    { key: 'A', text: 'Adventure', points: { Explorer: 3 } },
    { key: 'B', text: 'Heritage', points: { Culture: 3 } },
    { key: 'C', text: 'Beach', points: { Beach: 3 } },
    { key: 'D', text: 'Nightlife', points: { Social: 3, Urban: 2 } },
    { key: 'E', text: 'Wildlife', points: { Nature: 3, Explorer: 1 } },
  ]},
  { id: 5, text: 'Which quote fits you?', options: [
    { key: 'A', text: '"Life begins outside your comfort zone."', points: { Explorer: 3 } },
    { key: 'B', text: '"Every culture tells a story."', points: { Culture: 3 } },
    { key: 'C', text: '"Peace is listening to the waves."', points: { Beach: 3, Slow: 1 } },
    { key: 'D', text: '"Cities never sleep."', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: '"Nature feels like home."', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 6, text: 'Your ideal accommodation?', options: [
    { key: 'A', text: 'Campsite', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Heritage hotel', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Beach resort', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'City hotel', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Forest cabin', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 7, text: 'Favorite morning activity on vacation?', options: [
    { key: 'A', text: 'Trek', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Museum', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Sunrise on the beach', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Cafe hopping', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Nature walk', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 8, text: 'Best travel companion?', options: [
    { key: 'A', text: 'Adventure friends', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Family', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Partner', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'A big group', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Solo', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 9, text: 'Pick a meal.', options: [
    { key: 'A', text: 'Campfire BBQ', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Traditional local cuisine', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Fresh seafood', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Street food', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'A quiet picnic', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 10, text: 'Preferred way to get around?', options: [
    { key: 'A', text: 'Jeep', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Walking', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Boat', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Metro', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Cycle', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 11, text: 'What would you buy as a souvenir?', options: [
    { key: 'A', text: 'Trekking gear', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'A local handicraft', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Beachwear', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'A city print or fridge magnet', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'A handmade wooden carving', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 12, text: 'Favorite travel weather?', options: [
    { key: 'A', text: 'Cold, crisp mountain air', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Mild, perfect for sightseeing', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Sunny and tropical', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Warm city evenings', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Cool, misty mornings', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 13, text: 'Which festival would you travel for?', options: [
    { key: 'A', text: 'An adventure sports festival', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'A heritage & folk festival', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'A beach music festival', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'A city nightlife festival', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'A quiet harvest festival', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 14, text: 'Your trip planning style?', options: [
    { key: 'A', text: 'Loose plans, ready for the unexpected', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Research everything in detail', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Book a package and switch off', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Plan around food and nightlife', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Keep it simple and flexible', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 15, text: 'Biggest travel fear?', options: [
    { key: 'A', text: 'Missing out on adventure', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Not understanding the local culture', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'An overcrowded, noisy trip', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'A boring, uneventful city', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Being disconnected from nature', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 16, text: 'Choose a movie setting.', options: [
    { key: 'A', text: 'A remote mountain expedition', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'A historic palace drama', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'A dreamy island romance', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'A fast-paced city thriller', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'A quiet cabin in the woods', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 17, text: 'Perfect evening on a trip?', options: [
    { key: 'A', text: 'Stargazing after a long trek', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Wandering an old town at dusk', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Cocktails by the beach', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Rooftop bar with city lights', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'A quiet walk in the woods', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 18, text: 'How do you spend your travel budget?', options: [
    { key: 'A', text: "I'll rough it for more adventure", points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'I save for immersive cultural experiences', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'I splurge for beachfront comfort', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'I spend on nightlife and experiences', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'I keep costs minimal and simple', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 19, text: 'Favorite landscape?', options: [
    { key: 'A', text: 'Jagged mountains', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Ancient ruins and temples', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Turquoise coastline', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Glittering skyline', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Dense green forest', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 20, text: 'Dream weekend?', options: [
    { key: 'A', text: 'A spontaneous road trip into the unknown', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'A slow walk through a historic town', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Lying on a beach doing nothing', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: "Exploring a new city's bars and cafes", points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Camping by a quiet lake', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 21, text: 'Choose a hobby for your next trip.', options: [
    { key: 'A', text: 'Rock climbing', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Learning a local language', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Snorkeling', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Street photography', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Birdwatching', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 22, text: 'What do your friends call you, travel-wise?', options: [
    { key: 'A', text: '"The Adventurer"', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: '"The Historian"', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: '"The Relaxer"', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: '"The Socialite"', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: '"The Wanderer"', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 23, text: 'Ideal vacation pace?', options: [
    { key: 'A', text: 'Non-stop activity', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Deliberate and immersive', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Slow and indulgent', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Busy and social', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Calm and unhurried', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 24, text: 'Which memory would you treasure most?', options: [
    { key: 'A', text: 'Reaching a summit at sunrise', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Sharing a meal with a local family', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Floating in warm turquoise water', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Dancing at a rooftop party', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Watching wildlife in silence', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 25, text: 'Which animal encounter appeals to you?', options: [
    { key: 'A', text: 'Tracking snow leopards in the mountains', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Visiting a heritage elephant sanctuary', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Swimming with sea turtles', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'A city zoo and aquarium tour', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'A quiet birdwatching safari', points: { Nature: 3, Slow: 2 } },
  ]},

  { id: 26, text: 'You land in a new country with zero plans. First move?', options: [
    { key: 'A', text: 'Find the nearest trail or peak to climb', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Head straight to the oldest part of town', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Look for the closest beach', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Explore the busiest neighborhood', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Ask locals where to see wildlife or greenery', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 27, text: "Pick the trip that sounds most like 'you'.", options: [
    { key: 'A', text: 'A weekend bar-hopping through a buzzing city', points: { Urban: 3, Social: 2 } },
    { key: 'B', text: 'A silent retreat deep in a forest', points: { Nature: 3, Slow: 2 } },
    { key: 'C', text: 'A food crawl through unfamiliar street stalls', points: { Foodie: 3, Urban: 2 } },
    { key: 'D', text: 'A five-star stay with a private spa', points: { Luxury: 3, Beach: 2 } },
    { key: 'E', text: 'A shoestring trip with a backpack and no fixed plan', points: { Budget: 3, Explorer: 2 } },
  ]},
  { id: 28, text: 'How do you choose where to sleep on a trip?', options: [
    { key: 'A', text: 'Whatever has the best pool and room service', points: { Luxury: 3, Beach: 2 } },
    { key: 'B', text: 'Cheapest clean bed I can find', points: { Budget: 3, Explorer: 2 } },
    { key: 'C', text: 'Wherever the group is staying', points: { Social: 3, Urban: 2 } },
    { key: 'D', text: 'A quiet homestay, away from the crowd', points: { Slow: 3, Nature: 2 } },
    { key: 'E', text: "Doesn't matter — I'll be out exploring anyway", points: { Explorer: 3, Nature: 2 } },
  ]},
  { id: 29, text: 'Your itinerary for tomorrow is empty. How do you feel?', options: [
    { key: 'A', text: 'Relieved — a slow, unplanned day sounds perfect', points: { Slow: 3, Nature: 2 } },
    { key: 'B', text: 'Excited — time to improvise something adventurous', points: { Explorer: 3, Nature: 2 } },
    { key: 'C', text: "I'll fill it with a museum or historic site", points: { Culture: 3, Slow: 2 } },
    { key: 'D', text: 'Straight to the water', points: { Beach: 3, Luxury: 2 } },
    { key: 'E', text: "I'll wander into whatever part of the city looks lively", points: { Urban: 3, Social: 2 } },
  ]},
  { id: 30, text: 'Which of these would ruin a trip for you fastest?', options: [
    { key: 'A', text: 'No access to the sea or a pool', points: { Beach: 3, Luxury: 2 } },
    { key: 'B', text: 'A hotel far from anything happening', points: { Urban: 3, Social: 2 } },
    { key: 'C', text: 'No greenery or fresh air anywhere nearby', points: { Nature: 3, Slow: 2 } },
    { key: 'D', text: 'Bad food with no local options', points: { Foodie: 3, Urban: 2 } },
    { key: 'E', text: 'Uncomfortable, no-frills accommodation', points: { Luxury: 3, Beach: 2 } },
  ]},
  { id: 31, text: "What's non-negotiable when you travel?", options: [
    { key: 'A', text: 'Trying the local specialty dish, wherever it takes me', points: { Foodie: 3, Urban: 2 } },
    { key: 'B', text: 'A little bit of comfort and pampering', points: { Luxury: 3, Beach: 2 } },
    { key: 'C', text: 'Keeping costs as low as possible', points: { Budget: 3, Explorer: 2 } },
    { key: 'D', text: 'Having people to share the trip with', points: { Social: 3, Urban: 2 } },
    { key: 'E', text: "Not rushing — I'd rather see less, slowly", points: { Slow: 3, Nature: 2 } },
  ]},
  { id: 32, text: 'Your ideal group size for a trip?', options: [
    { key: 'A', text: 'As many people as possible — the more the merrier', points: { Social: 3, Urban: 2 } },
    { key: 'B', text: 'Just one or two close friends, no rush', points: { Slow: 3, Nature: 2 } },
    { key: 'C', text: 'A small crew ready for anything', points: { Explorer: 3, Nature: 2 } },
    { key: 'D', text: 'People who love history as much as I do', points: { Culture: 3, Slow: 2 } },
    { key: 'E', text: "Doesn't matter, as long as there's a beach", points: { Beach: 3, Luxury: 2 } },
  ]},
  { id: 33, text: 'Which souvenir would you actually bring home?', options: [
    { key: 'A', text: 'A piece of local art or craft with a story', points: { Culture: 3, Slow: 2 } },
    { key: 'B', text: 'A seashell or something from the shoreline', points: { Beach: 3, Luxury: 2 } },
    { key: 'C', text: 'A print of the city skyline', points: { Urban: 3, Social: 2 } },
    { key: 'D', text: 'A pressed leaf or rock from a trail', points: { Nature: 3, Slow: 2 } },
    { key: 'E', text: "A spice blend or recipe I can't get at home", points: { Foodie: 3, Urban: 2 } },
  ]},
  { id: 34, text: "What does 'a good trip' mean to you?", options: [
    { key: 'A', text: 'Time outdoors, away from screens and noise', points: { Nature: 3, Slow: 2 } },
    { key: 'B', text: 'Eating something unforgettable', points: { Foodie: 3, Urban: 2 } },
    { key: 'C', text: 'Being taken care of, no stress', points: { Luxury: 3, Beach: 2 } },
    { key: 'D', text: 'Coming back having spent almost nothing', points: { Budget: 3, Explorer: 2 } },
    { key: 'E', text: "Meeting people I'll stay in touch with", points: { Social: 3, Urban: 2 } },
  ]},
  { id: 35, text: 'Pick your travel motto.', options: [
    { key: 'A', text: "'See more, spend less.'", points: { Budget: 3, Explorer: 2 } },
    { key: 'B', text: "'The more, the merrier.'", points: { Social: 3, Urban: 2 } },
    { key: 'C', text: "'Wherever I am, I'm in no hurry.'", points: { Slow: 3, Nature: 2 } },
    { key: 'D', text: "'Say yes to everything.'", points: { Explorer: 3, Nature: 2 } },
    { key: 'E', text: "'Every place has a story worth learning.'", points: { Culture: 3, Slow: 2 } },
  ]},
  { id: 36, text: 'Which of these trip openers excites you most?', options: [
    { key: 'A', text: 'A sunrise hike on day one', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'A guided walk through the old quarter', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Checking into a beachfront room', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'A rooftop dinner overlooking the skyline', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'A quiet morning by a lake or forest', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 37, text: 'You have one evening free. What do you do?', options: [
    { key: 'A', text: 'Find the busiest street and just walk it', points: { Urban: 3, Social: 2 } },
    { key: 'B', text: 'Sit somewhere quiet and watch the sky change', points: { Nature: 3, Slow: 2 } },
    { key: 'C', text: 'Track down the best-reviewed local eatery', points: { Foodie: 3, Urban: 2 } },
    { key: 'D', text: 'Book a spa or a nice dinner, treat yourself', points: { Luxury: 3, Beach: 2 } },
    { key: 'E', text: "Find whatever's free or nearly free to do", points: { Budget: 3, Explorer: 2 } },
  ]},
  { id: 38, text: "What's your relationship with a travel budget?", options: [
    { key: 'A', text: "I'll happily overspend for the right experience", points: { Luxury: 3, Beach: 2 } },
    { key: 'B', text: 'I track every rupee and love a good bargain', points: { Budget: 3, Explorer: 2 } },
    { key: 'C', text: 'I split costs and plan around the group', points: { Social: 3, Urban: 2 } },
    { key: 'D', text: "Budget matters less than pace — I'd rather go slow", points: { Slow: 3, Nature: 2 } },
    { key: 'E', text: 'I spend on gear that gets me further off the beaten path', points: { Explorer: 3, Nature: 2 } },
  ]},
  { id: 39, text: 'Which of these would you happily do for an entire day?', options: [
    { key: 'A', text: 'Nothing — just sit somewhere beautiful', points: { Slow: 3, Nature: 2 } },
    { key: 'B', text: 'Push through a tough, rewarding trail', points: { Explorer: 3, Nature: 2 } },
    { key: 'C', text: 'Wander through temples, ruins or old streets', points: { Culture: 3, Slow: 2 } },
    { key: 'D', text: 'Float in the sea', points: { Beach: 3, Luxury: 2 } },
    { key: 'E', text: 'Explore a city block by block on foot', points: { Urban: 3, Social: 2 } },
  ]},
  { id: 40, text: "Your phone's about to die on a trip. What's the last photo?", options: [
    { key: 'A', text: 'The ocean at golden hour', points: { Beach: 3, Luxury: 2 } },
    { key: 'B', text: 'A crowded, glowing night market', points: { Urban: 3, Social: 2 } },
    { key: 'C', text: 'A mountain trail or forest canopy', points: { Nature: 3, Slow: 2 } },
    { key: 'D', text: "A plate of something you've never eaten before", points: { Foodie: 3, Urban: 2 } },
    { key: 'E', text: 'A five-star hotel room view', points: { Luxury: 3, Beach: 2 } },
  ]},
  { id: 41, text: 'What would you research most before a trip?', options: [
    { key: 'A', text: 'Restaurants and food markets', points: { Foodie: 3, Urban: 2 } },
    { key: 'B', text: 'The best hotels and upgrades available', points: { Luxury: 3, Beach: 2 } },
    { key: 'C', text: 'The cheapest flights and hostels', points: { Budget: 3, Explorer: 2 } },
    { key: 'D', text: "Who else is going and what they're up for", points: { Social: 3, Urban: 2 } },
    { key: 'E', text: 'Nothing much — I like to arrive and figure it out slowly', points: { Slow: 3, Nature: 2 } },
  ]},
  { id: 42, text: 'How do you feel about a trip with a packed schedule?', options: [
    { key: 'A', text: 'Love it — more people, more plans, more fun', points: { Social: 3, Urban: 2 } },
    { key: 'B', text: "I'd rather cut it in half and enjoy less, more deeply", points: { Slow: 3, Nature: 2 } },
    { key: 'C', text: "Fine, as long as there's room for spontaneous detours", points: { Explorer: 3, Nature: 2 } },
    { key: 'D', text: 'Only if it includes enough museums and history', points: { Culture: 3, Slow: 2 } },
    { key: 'E', text: "Only if there's beach time built in", points: { Beach: 3, Luxury: 2 } },
  ]},
  { id: 43, text: 'Which local experience appeals to you most?', options: [
    { key: 'A', text: 'A traditional ceremony or ritual', points: { Culture: 3, Slow: 2 } },
    { key: 'B', text: 'A quiet cove only locals know about', points: { Beach: 3, Luxury: 2 } },
    { key: 'C', text: 'A rooftop party with the city lit up below', points: { Urban: 3, Social: 2 } },
    { key: 'D', text: 'A guided walk spotting local wildlife', points: { Nature: 3, Slow: 2 } },
    { key: 'E', text: 'A cooking class with a local family', points: { Foodie: 3, Urban: 2 } },
  ]},
  { id: 44, text: "What's the first thing you check about a destination?", options: [
    { key: 'A', text: "What the landscape and outdoor access is like", points: { Nature: 3, Slow: 2 } },
    { key: 'B', text: 'What the local cuisine is known for', points: { Foodie: 3, Urban: 2 } },
    { key: 'C', text: 'What five-star options exist', points: { Luxury: 3, Beach: 2 } },
    { key: 'D', text: 'How affordable it is to get around', points: { Budget: 3, Explorer: 2 } },
    { key: 'E', text: 'How lively the social scene is', points: { Social: 3, Urban: 2 } },
  ]},
  { id: 45, text: "Pick the travel flex you'd actually brag about.", options: [
    { key: 'A', text: "'I did the whole trip on a shoestring budget.'", points: { Budget: 3, Explorer: 2 } },
    { key: 'B', text: "'I made friends with locals everywhere I went.'", points: { Social: 3, Urban: 2 } },
    { key: 'C', text: "'I stayed two weeks in one town and never rushed.'", points: { Slow: 3, Nature: 2 } },
    { key: 'D', text: "'I did the hardest trek there without a guide.'", points: { Explorer: 3, Nature: 2 } },
    { key: 'E', text: "'I learned the local language before I left.'", points: { Culture: 3, Slow: 2 } },
  ]},
  { id: 46, text: 'Which travel documentary would you actually finish watching?', options: [
    { key: 'A', text: 'Solo expedition across an unmapped trail', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'The rise and fall of an ancient civilization', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Island life on a remote coastline', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'A night in the life of a megacity', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Following migrating wildlife across a continent', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 47, text: "What's your travel dealbreaker?", options: [
    { key: 'A', text: 'A destination with nothing going on at night', points: { Urban: 3, Social: 2 } },
    { key: 'B', text: 'Nowhere quiet to just breathe', points: { Nature: 3, Slow: 2 } },
    { key: 'C', text: 'No interesting food scene', points: { Foodie: 3, Urban: 2 } },
    { key: 'D', text: 'No option to upgrade or treat myself', points: { Luxury: 3, Beach: 2 } },
    { key: 'E', text: 'Prices too high to stretch my trip further', points: { Budget: 3, Explorer: 2 } },
  ]},
  { id: 48, text: 'If someone else planned your entire trip, what would matter most?', options: [
    { key: 'A', text: "That it's comfortable and well taken care of", points: { Luxury: 3, Beach: 2 } },
    { key: 'B', text: "That it doesn't cost a fortune", points: { Budget: 3, Explorer: 2 } },
    { key: 'C', text: 'That there\'s a group to enjoy it with', points: { Social: 3, Urban: 2 } },
    { key: 'D', text: "That there's no rush anywhere", points: { Slow: 3, Nature: 2 } },
    { key: 'E', text: 'That there\'s room to go off-script', points: { Explorer: 3, Nature: 2 } },
  ]},
  { id: 49, text: 'Last day of the trip — how do you spend it?', options: [
    { key: 'A', text: 'Doing absolutely nothing, savoring it', points: { Slow: 3, Nature: 2 } },
    { key: 'B', text: 'Squeezing in one last adventure', points: { Explorer: 3, Nature: 2 } },
    { key: 'C', text: 'Revisiting your favorite historic spot', points: { Culture: 3, Slow: 2 } },
    { key: 'D', text: 'One final swim before you leave', points: { Beach: 3, Luxury: 2 } },
    { key: 'E', text: 'A last walk through the city that never slept', points: { Urban: 3, Social: 2 } },
  ]},
  { id: 50, text: 'What would make you say yes to a last-minute trip?', options: [
    { key: 'A', text: "Someone mentions a beach you've never seen", points: { Beach: 3, Luxury: 2 } },
    { key: 'B', text: "It's to a city you've always wanted to explore", points: { Urban: 3, Social: 2 } },
    { key: 'C', text: 'It involves a hike or a national park', points: { Nature: 3, Slow: 2 } },
    { key: 'D', text: "There's a food festival happening", points: { Foodie: 3, Urban: 2 } },
    { key: 'E', text: "It comes with an upgrade you can't refuse", points: { Luxury: 3, Beach: 2 } },
  ]},

  { id: 51, text: "You're offered two routes to a viewpoint. Which do you choose?", options: [
    { key: 'A', text: 'A challenging hiking trail', points: { Explorer: 3, Nature: 2, Budget: 1 } },
    { key: 'B', text: 'A historical walking path', points: { Culture: 3, Slow: 2, Nature: 1 } },
    { key: 'C', text: 'A scenic cable car', points: { Luxury: 3, Beach: 2, Urban: 1 } },
    { key: 'D', text: 'A lively city street', points: { Urban: 3, Social: 2, Foodie: 1 } },
    { key: 'E', text: 'A quiet forest trail', points: { Nature: 3, Slow: 2, Explorer: 1 } },
  ]},
  { id: 52, text: 'Which sound feels most relaxing?', options: [
    { key: 'A', text: 'Mountain wind', points: { Nature: 3, Explorer: 2 } },
    { key: 'B', text: 'Temple bells', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Ocean waves', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Busy streets', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Birdsong', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 53, text: 'Your dream travel photo post?', options: [
    { key: 'A', text: 'Summit selfie', points: { Explorer: 3, Social: 2 } },
    { key: 'B', text: 'Ancient ruins', points: { Culture: 3, Explorer: 2 } },
    { key: 'C', text: 'Beach hammock', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Neon skyline', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Lake reflection', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 54, text: 'Favorite travel movie genre?', options: [
    { key: 'A', text: 'Adventure', points: { Explorer: 3, Budget: 2 } },
    { key: 'B', text: 'Historical', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Romantic escape', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Modern city', points: { Urban: 3, Foodie: 2 } },
    { key: 'E', text: 'Nature documentary', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 55, text: 'If you could extend your trip by one day...', options: [
    { key: 'A', text: 'Try another activity', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Visit another museum', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Relax at the resort', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Explore the nightlife', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Watch sunrise in nature', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 56, text: 'Best travel gift you could receive?', options: [
    { key: 'A', text: 'Hiking gear', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'A history book', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'A spa voucher', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'A city pass', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'A camping kit', points: { Nature: 3, Explorer: 2 } },
  ]},
  { id: 57, text: 'What would you miss most after returning home?', options: [
    { key: 'A', text: 'The adventure', points: { Explorer: 3, Budget: 2 } },
    { key: 'B', text: 'The people and traditions', points: { Culture: 3, Social: 2 } },
    { key: 'C', text: 'The peace', points: { Beach: 3, Slow: 2 } },
    { key: 'D', text: 'The energy', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'The fresh air', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 58, text: 'Choose a weekend escape.', options: [
    { key: 'A', text: 'Mountains', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'Old town', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Island', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'Metro city', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'National park', points: { Nature: 3, Explorer: 2 } },
  ]},
  { id: 59, text: 'How do you usually travel?', options: [
    { key: 'A', text: 'Backpack', points: { Budget: 3, Explorer: 2 } },
    { key: 'B', text: 'Guidebook in hand', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Suitcase', points: { Luxury: 3, Beach: 2 } },
    { key: 'D', text: 'Camera around my neck', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Binoculars', points: { Nature: 3, Slow: 2 } },
  ]},
  { id: 60, text: 'Your ideal ending to a journey?', options: [
    { key: 'A', text: 'One more adventure', points: { Explorer: 3, Nature: 2 } },
    { key: 'B', text: 'A meaningful lesson', points: { Culture: 3, Slow: 2 } },
    { key: 'C', text: 'Total relaxation', points: { Beach: 3, Luxury: 2 } },
    { key: 'D', text: 'A big celebration', points: { Urban: 3, Social: 2 } },
    { key: 'E', text: 'Inner peace', points: { Nature: 3, Slow: 2 } },
  ]},
];

function pickRandomQuestions(count = 20) {
  const pool = [...QUIZ_BANK];
  const chosen = [];
  while (chosen.length < count && pool.length) {
    const idx = Math.floor(Math.random() * pool.length);
    chosen.push(pool.splice(idx, 1)[0]);
  }
  return chosen;
}
